### ISSUE TITLE
MPL license

### ISSUE THREAD

**Issue by vitiral** [dpc/cbuf-rs#7]
I was curious why you chose the MPL over the simpler MIT license?

Not that it matters too much, I just see the MIT as simpler and more permisive

**Comment by dpc** [comment]
Please don't read what I'm going to write too seriously. I enjoy getting drastic for fun.

MPL is my default for everything in Rust. I just want the code to stay open. It's kind of already a compromise - if it's not for the fact that I really, really like Rust (OK, I think I might be in love with Rust at this point), and want to help bootstrap it's ecosystem, I'd be making everything AGPL.

Normally I think licensing your work as MIT is a suckery (except for many cases when it makes sense; eg. when you're really bootstrapping something like programming language). You work your ass off, ruin health sitting and staring at the screen, give free support and free software, and companies are going to freeload on your work, to sell your privacy, serve ads, or charge money for using it at the end. You're going to pay for what you helped create, while some shareholders are getting rich (don't get me wrong, I own stocks myself and I want to be rich myself - nothing wrong with it). But they give you nothing in return as an engineer: still drag you to day-long interviews, examine like test subject, and make go jumps hoops to get hired etc. You gain absolutely nothing by using MIT over AGPL. I don't think CEOs anywhere ever go: "we have built $1B company using a lot of open source, let's now go and send every author of open source component that've used a 'thank you' check". Not even a t-shirt. ;D . If you want to use your open source as a proof of your skill, AGPL is not a problem.

If you publish your software as GPL/AGPL, other free software devs can still use it with no problem, and commercial entities that want to make money and can't give back to free software, can just contact you and ask for commercial license, and actually give you something back. Or they can hire someone (you maybe), and pay them from writing the software. So yeah... IMO, most of the time, by publishing MIT/BSD software, we're subsidizing the rich (big capital), and undercutting our fellow engineers.

Actually I'm not even really satisfied with AGPL, but oh well... it's the closest right now, and I'm in touch with licensing movement around CopyFair and "commons" movements.

**Comment by vitiral** [comment]
If my project (defrag-rs) uses this library in it's dependencies, can I still license it as MIT?

**Comment by vitiral** [comment]
I think that all makes sense -- for my project though I really want anyone to be able to use it for any reason because I want low power microcontrollers to be used in places where high power CPUs are currently used. I think buisness can be part of that and I don't mind people making money off my work :)

:+1: on what you said though :)

**Comment by dpc** [comment]
Yes. MPL does not enforce anything in your own project.

**Comment by vitiral** [comment]
gotcha -- so the MPL just means that any changes have to remain in the open source space (similar to GPL). I do like that... I might consider re-licensing

**Comment by dpc** [comment]
Yeap. I can recommend: https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2) . I am myself not a specialist in these matters.
