### ISSUE TITLE
upload version 1.1

### ISSUE THREAD

**Issue by vitiral** [dpc/cbuf-rs#8]
I think it is now fairly feature-complete. Can you upload version 1.1?

Thankyou

**Comment by dpc** [comment]
You should be able to do it already. https://crates.io/crates/cbuf lists you as a owner, so it should work.

**Comment by dpc** [comment]
I am happy to help review commits, but I think you can take over the real ownership of this crate, as you're actively working with it.

BTW. You can add yourself to `authors` in `Cargo.toml`.

**Comment by vitiral** [comment]
awesome, done and done!
